namespace: ansible
name: containers
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.unix: '>=1.0'
repository: git@github.com:coll-test/ansible.containers.git
documentation: https://github.com/coll-test/ansible.containers/tree/master/docs
homepage: https://github.com/coll-test/ansible.containers
issues: https://github.com/coll-test/ansible.containers/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
